FROM confluentinc/cp-kafka-connect-base:6.1.1

ENV KAFKA_CONNECT_PELION_VERSION 1.0.1

  # add some sample connectors
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-elasticsearch:11.0.3 \
&& confluent-hub install --no-prompt confluentinc/kafka-connect-s3:10.0.0 \
&& confluent-hub install --no-prompt confluentinc/kafka-connect-http:1.2.2

  # install kafka-connect-pelion connector
RUN curl -k -SL https://github.com/PelionIoT/kafka-connect-pelion/releases/download/kafka-connect-pelion-parent-${KAFKA_CONNECT_PELION_VERSION}/pelion-kafka-connect-pelion-${KAFKA_CONNECT_PELION_VERSION}.zip -o /tmp/kafka-connect-pelion.zip \
&& confluent-hub install --no-prompt /tmp/kafka-connect-pelion.zip \
&& rm /tmp/kafka-connect-pelion.zip